apiVersion: v1
kind: Service
metadata:
  name: inventory-service
spec:
  selector:
    app: inventory-service-api
  ports:
  - protocol: "TCP"
    port: 5000
    targetPort: 8000
  type: LoadBalancer

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: inventory-service-api
spec:
  selector:
    matchLabels:
      app: inventory-service-api
  replicas: 5
  template:
    metadata:
      labels:
        app: inventory-service-api
    spec:
      containers:
      - name: inventory-service-api
        image: django-inventory-service
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8000