apiVersion: v1
kind: Service
metadata:
  name: student-service
spec:
  selector:
    app: student-service-api
  ports:
  - protocol: "TCP"
    port: 8000
    targetPort: 8080
  type: LoadBalancer

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: student-service-api
spec:
  selector:
    matchLabels:
      app: student-service-api
  replicas: 2
  template:
    metadata:
      labels:
        app: student-service-api
    spec:
      containers:
      - name: student-service-api
        image: npm-java-student-service
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080